//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.1433
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LedMatrixDevArea.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LedMatrixDevArea.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;LedMatrixSymbolFile Comments=&quot;No comments&quot;&gt;
        ///	&lt;LedMatrixSymbolFont FontName=&quot;Default&quot;&gt;
        ///		&lt;LedMatrixSymbol SymbolCode=&quot;32&quot; Description=&quot;Space&quot;&gt;
        ///			&lt;LedLine LineNumber=&quot;0&quot; LineLedOn=&quot;__&quot;/&gt;
        ///		    &lt;LedLine LineNumber=&quot;1&quot; LineLedOn=&quot;__&quot;/&gt;
        ///		    &lt;LedLine LineNumber=&quot;2&quot; LineLedOn=&quot;__&quot;/&gt;
        ///		    &lt;LedLine LineNumber=&quot;3&quot; LineLedOn=&quot;__&quot;/&gt;
        ///		    &lt;LedLine LineNumber=&quot;4&quot; LineLedOn=&quot;__&quot;/&gt;
        ///			&lt;LedLine LineNumber=&quot;5&quot; LineLedOn=&quot;__&quot;/&gt;
        ///			&lt;LedLine LineNumber=&quot;6&quot; LineLedOn=&quot;__&quot;/&gt;        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LedMatrixSymbolFile {
            get {
                return ResourceManager.GetString("LedMatrixSymbolFile", resourceCulture);
            }
        }
    }
}
